import { arrow_right_icon } from "../../assets/resources/icons";
import {
  home_image,
  kitchen_image,
  bedroom_image,
  article1,
  article2,
  article3,
  article4,
  article5,
  article6,
} from "../../assets/resources/images";
export const articleItem = [
  {
    id: 1,
    image: `${home_image}`,
    title: "7ways to decor your home ",
    link: "Read More",
    icons: `${arrow_right_icon}`,
    date: "october 16, 2023",
  },
  {
    id: 2,
    image: `${kitchen_image}`,
    title: " Kitchen organization",
    link: "Read More",
    icons: `${arrow_right_icon}`,
    date: "october 16, 2023",
  },
  {
    id: 3,
    image: `${bedroom_image}`,
    title: "Decor your Bedroom ",
    link: "Read More",
    icons: `${arrow_right_icon}`,
    date: "october 16, 2023",
  },
  {
    id: 4,
    image: `${article1}`,
    title: "Modern texas home is beautiful and completely kid-friendly",
    link: "",
    icons: "",
    date: "october 16, 2023",
  },
  {
    id: 5,
    image: `${article2}`,
    title: "Modern texas home is beautiful and completely kid-friendly",
    link: "",
    icons: "",
    date: "october 16, 2023",
  },
  {
    id: 6,
    image: `${article3}`,
    title: "Modern texas home is beautiful and completely kid-friendly",
    link: "",
    icons: "",
    date: "october 16, 2023",
  },
  {
    id: 7,
    image: `${article4}`,
    title: "Modern texas home is beautiful and completely kid-friendly",
    link: "",
    icons: "",
    date: "october 16, 2023",
  },
  {
    id: 8,
    image: `${article5}`,
    title: "Modern texas home is beautiful and completely kid-friendly",
    link: "",
    icons: "",
    date: "october 16, 2023",
  },
  {
    id: 9,
    image: `${article6}`,
    title: "Modern texas home is beautiful and completely kid-friendly",
    link: "",
    icons: "",
    date: "october 16, 2023",
  },
];
